server:
  port: 8989
logging:
  level:
    manoj: DEBUG
spring:
  application:
    name: SECURITY-SERVICE
  cloud:
    config:
      profile: main
  config:
    import: configserver:http://localhost:8888/Configuration